apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordsearch
  namespace: wordsearch
  labels:
    app: wordsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordsearch
  template:
    metadata:
      labels:
        app: wordsearch
    spec:
      imagePullSecrets:
        - name: pull-secret

      containers:
      - name: frontend
        image: wordsearchproject/frontend:0.0.cheese
        ports:
        - containerPort: 5000
      - name: backend
        image: wordsearchproject/backend:0.0.burger
        ports:
        - containerPort: 3000
