apiVersion: apps/v1
kind: Pod
metadata:
  name: diagnostics
  labels:
      app: diagnostics
spec:
  containers:
  - name: network-tools
    image: jonlabelle/network-tools
  tolerations:
  - key: "node.kubernetes.io/disk-pressure"
    operator: "Exists"
    effect: "NoSchedule"
