version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    networks:
      - backend
    environment:
      - API_ADDR=http://backend:5000

  backend:
    hostname: backend
    build: ./api
    ports:
      - "5000:5000"
    networks:
      - backend

networks:
  backend:
    driver: bridge
