# Ansible playbook for deploying a Flask app
# Credit to:
# https://github.com/brennv/flask-ansible-example.git
---
# Install system apt packages
- hosts: wsp
  become: yes
  become_method: sudo

  tasks:
  - name: sync backend folder
    synchronize:
      src: ../app/api/
      dest: /home/ubuntu/backend

  - name: Install required packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - python3-pip 
      - python3-dev 
      - build-essential 
      - libssl-dev 
      - libffi-dev 
      - python3-setuptools
    when: false

  - name: Install python dependencies
    pip:
      requirements: /home/ubuntu/backend/requirements.txt

  - name: Install service
    copy:
      src: wordsearch_api.service
      dest: /etc/systemd/system/wordsearch_api.service

  - name: Enable service
    service:
      name: wordsearch_api.service
      state: restarted
      enabled: yes
      daemon_reload: true
