# Ansible playbook for deploying a Flask app
# Credit to:
# https://github.com/brennv/flask-ansible-example.git
---
# Install system apt packages
- hosts: wsp
  become: yes
  become_method: sudo
  tasks:
  - name: Install required packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - python3-pip 
      - python3-dev 
      - build-essential 
      - libssl-dev 
      - libffi-dev 
      - python3-setuptools

